services:
  django:
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "
        while ! nc -z postgres 5432; do
          echo 'Waiting for postgres...';
          sleep 1;
        done;
        while ! nc -z redis 6379; do
          echo 'Waiting for redis...';
          sleep 1;
        done;
        # Commented out database reset - uncomment if you need a fresh start
        # echo 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;' | python tr_django/manage.py dbshell &&
        python tr_django/manage.py migrate &&
        python tr_django/manage.py seed_users &&
        python tr_django/manage.py seed_tournaments &&
        python tr_django/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/backend/django:/app
    ports:
      - "8000:8000"
    environment:
      - Debug=True
      - ENVIRONMENT=development
  nginx:
    build:
      context: ./src
      dockerfile: ./nginx/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ./src/frontend/:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - ENVIRONMENT=development
