services:
  django:
    command: sh -c "python tr_django/manage.py migrate && daphne -b 0.0.0.0 -p 8000 tr_django.asgi:application"
    ports:
      - "443:443"
    environment:
      - Debug=False
      - ENVIRONMENT=production
  nginx:
    build:
      context: ./src
      dockerfile: ./nginx/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ./src/frontend/:/usr/share/nginx/html
      - ./media:/var/www/media
    environment:
      - ENVIRONMENT=production
