# Generated by Django 5.1.2 on 2024-12-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
