# Generated by Django 5.1.2 on 2024-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_notification_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="message",
            new_name="content",
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default="default_type", max_length=50),
        ),
    ]
