# Generated by Django 5.1.1 on 2024-09-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(blank=True, null=True, to="game.player"),
        ),
    ]
