# Generated by Django 5.1.2 on 2024-11-01 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_gamemode_allow_both_conditions_gamemode_ball_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directeliminationtournamentgame",
            name="date",
        ),
        migrations.RemoveField(
            model_name="directeliminationtournamentgame",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="singlegame",
            name="date",
        ),
        migrations.RemoveField(
            model_name="singlegame",
            name="duration",
        ),
        migrations.AddField(
            model_name="directeliminationtournamentgame",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directeliminationtournamentgame",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directeliminationtournamentgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="playergamestats",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="singlegame",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="singlegame",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="singlegame",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="singlegame",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="directeliminationtournamentgame",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="directeliminationtournamentgame",
            name="mode",
            field=models.ForeignKey(
                help_text="Defines game rules and player requirements",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.gamemode",
            ),
        ),
        migrations.AlterField(
            model_name="directeliminationtournamentgame",
            name="players",
            field=models.ManyToManyField(
                related_name="%(class)s_games",
                through="game.PlayerGameStats",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="directeliminationtournamentgame",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_%(class)s_games",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="playergamestats",
            name="rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playergamestats",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="singlegame",
            name="mode",
            field=models.ForeignKey(
                help_text="Defines game rules and player requirements",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.gamemode",
            ),
        ),
        migrations.AlterField(
            model_name="singlegame",
            name="players",
            field=models.ManyToManyField(
                related_name="%(class)s_games",
                through="game.PlayerGameStats",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="singlegame",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_%(class)s_games",
                to="game.player",
            ),
        ),
    ]
