# Generated by Django 5.1.2 on 2024-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_directeliminationtournamentgame_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergamestats",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
