# Generated by Django 5.0.9 on 2024-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_auto_20241019_1219"),
        ("user", "0003_alter_userprofile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(to="user.userprofile"),
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
