# Generated by Django 5.0.9 on 2024-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_player_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="user.userprofile"),
        ),
    ]
