# Generated by Django 5.0.9 on 2024-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(to="user.userprofile"),
        ),
    ]
