# Generated by Django 5.0.9 on 2024-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userprofile_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friend_requests_sent",
            field=models.ManyToManyField(
                blank=True,
                related_name="friend_requests_received",
                to="user.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="user.userprofile"),
        ),
    ]
