# Generated by Django 5.0.9 on 2024-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_userprofile_friend_requests_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="friend_requests_sent",
            field=models.ManyToManyField(
                related_name="friend_requests_received", to="user.userprofile"
            ),
        ),
    ]
