# Generated by Django 5.1.1 on 2024-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_y', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=100.0)),
                ('width', models.FloatField(default=10.0)),
            ],
        ),
    ]
