# Generated by Django 5.1.2 on 2024-11-26 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 13, 55, 7, 612156, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 26, 14, 55, 7, 613363, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
