# Generated by Django 5.1.2 on 2024-11-26 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 14, 10, 53, 354752, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 26, 15, 10, 53, 355145, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
