# Generated by Django 5.1.2 on 2024-10-31 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
