# Generated by Django 5.1.2 on 2024-10-31 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friend_requests_sent",
            field=models.ManyToManyField(
                blank=True,
                related_name="friend_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
