# Generated by Django 5.1.2 on 2024-12-01 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0007_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="two_factor_method",
            field=models.CharField(
                choices=[
                    ("TOTP", "TOTP (Authenticator App)"),
                    ("SMS", "SMS"),
                    ("Email", "Email"),
                    ("Push", "Push Notification"),
                    ("Backup Codes", "Backup Codes"),
                    ("Hardware Token", "Hardware Token"),
                    ("Biometric", "Biometric Authentication"),
                ],
                default="Email",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 2, 16, 57, 15, 61292, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 17, 57, 15, 61761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email",),
                name="unique_email_when_not_null",
            ),
        ),
    ]
