# Generated by Django 5.1.2 on 2024-12-01 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_options_customuser_two_factor_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="two_factor_code_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 2, 17, 6, 2, 245255, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 18, 6, 2, 245891, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
