# Generated by Django 5.1.2 on 2024-11-15 17:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True, related_name="user_blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 16, 17, 19, 23, 828727, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 15, 18, 19, 23, 829548, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
