# Generated by Django 5.1.2 on 2024-12-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_emailverificationtoken_expires_at_and_more"),
        ("users", "0009_customuser_two_factor_code_expires_at_and_more"),
    ]

    operations = []
