# Generated by Django 5.1.2 on 2024-12-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_emailverificationtoken_expires_at_and_more"),
        ("users", "0010_merge_20241202_1928"),
    ]

    operations = []
