# Generated by Django 5.1.2 on 2024-11-13 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 14, 18, 11, 35, 554277, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 13, 19, 11, 35, 554680, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
