# Generated by Django 5.1.2 on 2024-11-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_blocked_users_and_more"),
        ("users", "0012_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = []
