# Generated by Django 5.1.2 on 2024-11-16 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 17, 19, 51, 54, 439460, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 16, 20, 51, 54, 439801, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
