# Generated by Django 5.1.2 on 2024-11-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_20241116_1358"),
        ("users", "0015_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = []
