# Generated by Django 5.1.2 on 2024-11-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_20241116_1000"),
        ("users", "0016_merge_20241117_1258"),
        ("users", "0032_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = []
